name: mlops
channels:
  - nodefaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.10
  - mlflow=2.4.0
  - gmpy2==2.1.2
  - pandas=1.5.3
  - numpy==1.23.5
  - scikit-learn=1.2.2
  - conda-forge::ncurses
platforms:
  - linux-64